### ISSUE TITLE
Package dist files for the latest commit

### ISSUE THREAD

**Issue by sanketsaurav** [doselect/ng-context-menu#1]
I've made some behavioral changes with [this](https://github.com/doselect/ng-context-menu/commit/84dceb0d8f5a66e83547a7a296231cf966067124) commit in the `development` branch. Please generate the packaged dist files, so we can use it on Desmond.

**Comment by dolftax** [comment]
Find it here - https://raw.githubusercontent.com/doselect/ng-context-menu/development/dist/ng-context-menu.min.js
